name: Auto Publish News

on:
  schedule:
    # 每天UTC时间0点（北京时间8点）触发
    - cron: '0 6 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  publish-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Run News Bot
      env:
        WECHAT_APPID: ${{ secrets.WECHAT_APPID }}
        WECHAT_SECRET: ${{ secrets.WECHAT_SECRET }}
        TIANAPI_KEY: ${{ secrets.TIANAPI_KEY }} 
      run: python news_bot.py
